### ISSUE TITLE
AttributeError on run

### ISSUE THREAD

**Issue by flavienbwk** [k3karthic/bitwarden-to-keepass#12]
Hi, using a JSON dump from a [Vaultwarden](https://github.com/dani-garcia/vaultwarden) instance, I get the following error :

```
$ bw2kp -o bitwarden.kdbx -i mydump.json
Master Password: 

Fetching folders...
Fetching items...
Traceback (most recent call last):
  File "/home/administrateur/.local/bin/bw2kp", line 8, in <module>
    sys.exit(main())
  File "/home/administrateur/.local/lib/python3.10/site-packages/bitwarden_to_keepass/convert.py", line 328, in main
    convert(vars(args))
  File "/home/administrateur/.local/lib/python3.10/site-packages/bitwarden_to_keepass/convert.py", line 272, in convert
    kp_db.items_to_entries(bw_vault.fetch_bitwarden_items())
  File "/home/administrateur/.local/lib/python3.10/site-packages/bitwarden_to_keepass/convert.py", line 217, in items_to_entries
    self.kp_db.add_entry(dest_group, title, username, password, url=url, notes=notes, otp=totp)
  File "/home/administrateur/.local/lib/python3.10/site-packages/pykeepass/pykeepass.py", line 531, in add_entry
    destination_group.append(entry)
AttributeError: 'NoneType' object has no attribute 'append'
```

**Comment by k3karthic** [comment]
Apologies, I had a personal emergency and did not have the time to look into this issue.

I'm not sure how a null group was added for the given folderId. For now, I've added a check which will fall back to the root if this happens.

I've never used VaultWarden before, will create a sample vault and see if I can reproduce the issue.
