### ISSUE TITLE
Not working with non encrypted JSON organization

### ISSUE THREAD

**Issue by stuxve** [k3karthic/bitwarden-to-keepass#14]
Trowing an error when convention:

```
Master Password:

Fetching folders...
Traceback (most recent call last):
  File "/home/kali/bitwarden-to-keepass/bitwarden_to_keepass/convert.py", line 332, in <module>
    main()
  File "/home/kali/bitwarden-to-keepass/bitwarden_to_keepass/convert.py", line 328, in main
    convert(vars(args))
  File "/home/kali/bitwarden-to-keepass/bitwarden_to_keepass/convert.py", line 269, in convert
    kp_db.folders_to_groups(bw_vault.fetch_bitwarden_folders())
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/bitwarden-to-keepass/bitwarden_to_keepass/convert.py", line 48, in fetch_bitwarden_folders
    self.folders = self.vault["folders"]
                   ~~~~~~~~~~^^^^^^^^^^^
KeyError: 'folders'

```

**Comment by VanLampe** [comment]
@stuxve I had the same issue, it happens if your export does not contain any folders but only items.

Catch the exception and return an empty list inside the method `fetch_bitwarden_folders` as follows worked for me:

```
    def fetch_bitwarden_folders(self):
        """List folders from bw cli or provided vault"""

        if self.vault is not None:
            try:
                self.folders = self.vault["folders"]
                return self.folders
            except KeyError:
                return []
```

**Comment by k3karthic** [comment]
Thanks for the issue report, I've updated the script to handle a vault json with no "folders" key in PR #15
