### ISSUE TITLE
AttributeError: module 'convert' has no attribute 'main'

### ISSUE THREAD

**Issue by firecat53** [k3karthic/bitwarden-to-keepass#6]
After installing to a fresh venv, I get the following error:

	$ python -m venv venv
	$ source venv/bin/activate
	$ pip install .
	$ bw2kp -h
	Traceback (most recent call last):
	  File "/home/firecat53/docs/family/scott/src/projects/bitwarden-to-keepass/venv/bin/bw2kp", line 33, in <module>
		sys.exit(load_entry_point('bitwarden-to-keepass==0.1.6', 'console_scripts', 'bw2kp')())
	  File "/home/firecat53/docs/family/scott/src/projects/bitwarden-to-keepass/venv/bin/bw2kp", line 25, in importlib_load_entry_point
		return next(matches).load()
	  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 173, in load
		return functools.reduce(getattr, attrs, module)
	AttributeError: module 'convert' has no attribute 'main'
	
Thanks!

**Comment by k3karthic** [comment]
I'm extremely sorry, I had pushed v0.1.6 without testing the pip installation method. I've pushed a fix, and you should be able to use it now. Going forward, I'll make sure to thoroughly test the project before pushing a build.

Regards,
Karthic Kumaran

**Comment by firecat53** [comment]
No worries! I've had to release many fixes for my fixes! Seems to be fine now,
thanks!
